x = np.arange(lb,ub,1) 
plt.style.use('fivethirtyeight')
ax.plot(x, norm.pdf(x, mean,sd) ,label="Default Class")
ax.set(title="STANDARDIZED DATA")
y = norm.pdf(x,mean,sd) 
xq3 = np.arange(q3, ub,1)
yq3 = norm.pdf(xq3, mean, sd)
xq1 = np.arange(lb, q1,1)
yq1 = norm.pdf(xq1, mean, sd)
ax.fill_between(xq3,yq3,0, alpha=.3, color='r', label="Q3: " +str(q3) +"\nOutliers > " +str(upper_outliers)+" :: QTY: " +str(len(stand_default[(stand_default >upper_outliers)])))
ax.fill_between(xq1,yq1,0, alpha=.3, color='g', label="Q1: " +str(q1) +"\nOutliers < " +str(lower_outliers)+" :: QTY: " + str(len(stand_default[(stand_default < lower_outliers)])))
plt.legend()
plt.show()